"""Local ICD index loader."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from .normalize import normalize_aggressive, normalize_conservative


class ICDIndex:
    """Read-only local ICD indexes generated by scripts/build_icd_index.py."""

    def __init__(self, index_dir: str | Path = "data/processed") -> None:
        self.index_dir = Path(index_dir)
        self.by_code: dict[str, dict[str, Any]] = self._load_json("icd_tt06_by_code.json")
        self.by_name: dict[str, list[str]] = self._load_json("icd_tt06_by_name.json")
        self.children: dict[str, list[str]] = self._load_json("icd_tt06_children.json")
        self.aliases: dict[str, dict[str, Any]] = self._load_yaml("icd_tt06_aliases.yaml")
        self.nodes = list(self.by_code.values())
        self._alias_lookup = self._build_alias_lookup()

    def _load_json(self, filename: str) -> Any:
        path = self.index_dir / filename
        if not path.exists():
            return {}
        return json.loads(path.read_text(encoding="utf-8"))

    def _load_yaml(self, filename: str) -> dict[str, dict[str, Any]]:
        path = self.index_dir / filename
        if not path.exists():
            return {}
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return data

    def _build_alias_lookup(self) -> dict[str, dict[str, Any]]:
        lookup: dict[str, dict[str, Any]] = {}
        for alias, payload in self.aliases.items():
            entry = dict(payload or {})
            entry["alias"] = alias
            for key in {normalize_conservative(alias), normalize_aggressive(alias)}:
                if key:
                    lookup[key] = entry
        return lookup

    def get_code(self, code: str | None) -> dict[str, Any] | None:
        if not code:
            return None
        return self.by_code.get(code.upper())

    def lookup_alias(self, text: str) -> dict[str, Any] | None:
        return self._alias_lookup.get(normalize_conservative(text)) or self._alias_lookup.get(
            normalize_aggressive(text)
        )

    def lookup_name(self, text: str) -> dict[str, Any] | None:
        for key in (normalize_conservative(text), normalize_aggressive(text)):
            codes = self.by_name.get(key)
            if codes:
                return self.get_code(codes[0])
        return None

    def child_nodes(self, code: str) -> list[dict[str, Any]]:
        return [node for child_code in self.children.get(code, []) if (node := self.get_code(child_code))]

    def get_parent(self, code: str) -> str | None:
        node = self.get_code(code)
        if not node:
            return None
        parent = node.get("parent_code")
        return str(parent).upper() if parent else None

    def get_children(self, code: str) -> list[str]:
        return list(self.children.get(str(code).upper(), []))

    def get_siblings(self, code: str) -> list[str]:
        canonical = str(code).upper()
        parent = self.get_parent(canonical)
        if not parent:
            return []
        return [sibling for sibling in self.get_children(parent) if sibling != canonical]

    def get_family_code(self, code: str) -> str | None:
        canonical = str(code).upper()
        if not self.get_code(canonical):
            return None
        return self.get_parent(canonical) or canonical

    def get_family_members(self, code: str) -> list[str]:
        family = self.get_family_code(code)
        if not family:
            return []
        children = self.get_children(family)
        return children or [family]

    def fuzzy_choices(self) -> list[tuple[str, str, str, str]]:
        choices: list[tuple[str, str, str, str]] = []
        for node in self.nodes:
            if node.get("level") in {"chapter", "section"}:
                continue
            code = node.get("code")
            name = node.get("name_vi", "")
            if code:
                choices.append((node.get("normalized_name", ""), code, name, "official_name"))
                choices.append(
                    (
                        node.get("normalized_name_with_accents", ""),
                        code,
                        name,
                        "official_name",
                    )
                )
        for alias, payload in self.aliases.items():
            code = payload.get("code")
            node = self.get_code(code)
            if code and node:
                choices.append((normalize_aggressive(alias), code, node.get("name_vi", ""), "alias"))
        return choices
